services:
  - type: web
    name: device-box-tracker
    env: docker
    plan: starter      # 7 €-Plan (damit Disk erlaubt)
    disk:
      name: sqlite-disk
      mountPath: /app/server
      sizeGB: 1
    envVars:
      - key: JWT_SECRET
        generateValue: true
