services:
  - type: web
    name: device-box-tracker
    env: docker
    plan: starter
    disk:
      name: sqlite-disk
      mountPath: /app/server/database
      sizeGB: 1
    envVars:
      - key: JWT_SECRET
        generateValue: true
